branch-defaults:
  master:
    environment: nextinteger-api
environment-defaults:
  nextinteger-api:
    branch: null
    repository: null
global:
  application_name: nextinteger
  default_ec2_keyname: aws-eb
  default_platform: Python 3.7 running on 64bit Amazon Linux 2
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application
