# Generated by Django 3.0.8 on 2020-07-26 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_socialauthuser"),
    ]

    operations = [
        migrations.AlterField(
            model_name="socialauthuser",
            name="access_token",
            field=models.CharField(max_length=512),
        ),
    ]
