# Generated by Django 3.0.8 on 2020-07-26 06:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_auto_20200726_0611"),
    ]

    operations = [
        migrations.RemoveField(model_name="socialauthuser", name="access_token",),
        migrations.AddField(
            model_name="socialauthuser",
            name="email",
            field=models.EmailField(
                default=django.utils.timezone.now, max_length=254, unique=True
            ),
            preserve_default=False,
        ),
    ]
